/**
 * AniList tag names the Ask companion may search with — a snapshot of
 * MediaTagCollection (non-adult, minus technical/format-only tags).
 * Spoiler-flagged tags are kept: searching by "reincarnation" because the
 * user asked for it spoils nothing. Anything the model proposes outside this
 * list is dropped before it reaches an AniList query, since an unknown
 * tag_in value matches nothing.
 */
export const TAG_VOCAB = [
  "Achronological Order",
  "Acrobatics",
  "Acting",
  "Adoption",
  "Afterlife",
  "Age Gap",
  "Age Regression",
  "Agender",
  "Agriculture",
  "Airsoft",
  "Alchemy",
  "Aliens",
  "Alternate Universe",
  "American Football",
  "Amnesia",
  "Anachronism",
  "Ancient China",
  "Angels",
  "Animals",
  "Anthology",
  "Anthropomorphism",
  "Anti-Hero",
  "Archery",
  "Aromantic",
  "Arranged Marriage",
  "Artificial Intelligence",
  "Asexual",
  "Assassins",
  "Astronomy",
  "Athletics",
  "Augmented Reality",
  "Autobiographical",
  "Aviation",
  "Badminton",
  "Ballet",
  "Band",
  "Bar",
  "Baseball",
  "Basketball",
  "Battle Royale",
  "Biographical",
  "Bisexual",
  "Blackmail",
  "Board Game",
  "Boarding School",
  "Body Horror",
  "Body Image",
  "Body Swapping",
  "Bowling",
  "Boxing",
  "Boys' Love",
  "Brainwashing",
  "Bullying",
  "Butler",
  "CGI",
  "Calligraphy",
  "Camping",
  "Cannibalism",
  "Card Battle",
  "Cars",
  "Centaur",
  "Cheating",
  "Cheerleading",
  "Chibi",
  "Chimera",
  "Chuunibyou",
  "Circus",
  "Class Struggle",
  "Classic Literature",
  "Classical Music",
  "Clone",
  "Coastal",
  "Cohabitation",
  "College",
  "Coming of Age",
  "Conspiracy",
  "Cosmic Horror",
  "Cosplay",
  "Cowboys",
  "Creature Taming",
  "Crime",
  "Criminal Organization",
  "Crossdressing",
  "Crossover",
  "Cult",
  "Cultivation",
  "Curses",
  "Cute Boys Doing Cute Things",
  "Cute Girls Doing Cute Things",
  "Cyberpunk",
  "Cyborg",
  "Cycling",
  "Dancing",
  "Death Game",
  "Delinquents",
  "Demons",
  "Denpa",
  "Desert",
  "Detective",
  "Dinosaurs",
  "Disability",
  "Dissociative Identities",
  "Dragons",
  "Drawing",
  "Drugs",
  "Dullahan",
  "Dungeon",
  "Dystopian",
  "E-Sports",
  "Eco-Horror",
  "Economics",
  "Educational",
  "Elderly Protagonist",
  "Elf",
  "Ensemble Cast",
  "Environmental",
  "Episodic",
  "Ero Guro",
  "Espionage",
  "Estranged Family",
  "Exiled",
  "Exorcism",
  "Fairy",
  "Fairy Tale",
  "Fake Relationship",
  "Family Life",
  "Fashion",
  "Female Harem",
  "Female Protagonist",
  "Femboy",
  "Fencing",
  "Filmmaking",
  "Firefighters",
  "Fishing",
  "Fitness",
  "Food",
  "Football",
  "Foreign",
  "Found Family",
  "Fugitive",
  "Full CGI",
  "Gambling",
  "Gangs",
  "Gender Bending",
  "Ghost",
  "Go",
  "Goblin",
  "Gods",
  "Golf",
  "Gore",
  "Guns",
  "Gyaru",
  "Handball",
  "Henshin",
  "Heterosexual",
  "Hikikomori",
  "Hip-hop Music",
  "Historical",
  "Homeless",
  "Horticulture",
  "Human Experimentation",
  "Ice Sports",
  "Idol",
  "Incest",
  "Indigenous Cultures",
  "Inn",
  "Inseki",
  "Interspecies",
  "Isekai",
  "Iyashikei",
  "Jazz Music",
  "Judo",
  "Kabuki",
  "Kaiju",
  "Karuta",
  "Kemonomimi",
  "Kingdom Management",
  "Konbini",
  "Kuudere",
  "LGBTQ+ Themes",
  "Lacrosse",
  "Language Barrier",
  "Lost Civilization",
  "Love Triangle",
  "Mafia",
  "Magic",
  "Mahjong",
  "Maids",
  "Makeup",
  "Male Harem",
  "Male Protagonist",
  "Manzai",
  "Marriage",
  "Martial Arts",
  "Matchmaking",
  "Matriarchy",
  "Medicine",
  "Medieval",
  "Memory Manipulation",
  "Mermaid",
  "Meta",
  "Metal Music",
  "Middle East",
  "Military",
  "Mixed Gender Harem",
  "Modeling",
  "Monster Boy",
  "Monster Girl",
  "Mopeds",
  "Motorcycles",
  "Mountaineering",
  "Musical Theater",
  "Mythology",
  "Natural Disaster",
  "Necromancy",
  "Nekomimi",
  "Ninja",
  "No Dialogue",
  "Noir",
  "Non-fiction",
  "Nudity",
  "Nun",
  "Office",
  "Office Lady",
  "Oiran",
  "Ojou-sama",
  "Orphan",
  "Otaku Culture",
  "Outdoor Activities",
  "Pandemic",
  "Parenthood",
  "Parkour",
  "Parody",
  "Philosophy",
  "Photography",
  "Pirates",
  "Poker",
  "Police",
  "Politics",
  "Polyamorous",
  "Post-Apocalyptic",
  "Pregnancy",
  "Primarily Adult Cast",
  "Primarily Animal Cast",
  "Primarily Child Cast",
  "Primarily Female Cast",
  "Primarily Male Cast",
  "Primarily Teen Cast",
  "Prison",
  "Prophecy",
  "Proxy Battle",
  "Psychosexual",
  "Rakugo",
  "Real Robot",
  "Rehabilitation",
  "Reincarnation",
  "Religion",
  "Rescue",
  "Restaurant",
  "Revenge",
  "Reverse Isekai",
  "Robots",
  "Rock Music",
  "Rotoscoping",
  "Royal Affairs",
  "Rugby",
  "Rural",
  "Samurai",
  "Satire",
  "School",
  "School Club",
  "Scuba Diving",
  "Shapeshifting",
  "Ships",
  "Shogi",
  "Shrine Maiden",
  "Skateboarding",
  "Skeleton",
  "Slapstick",
  "Slavery",
  "Snowscape",
  "Software Development",
  "Space",
  "Space Opera",
  "Spearplay",
  "Steampunk",
  "Stop Motion",
  "Succubus",
  "Suicide",
  "Sumo",
  "Super Power",
  "Super Robot",
  "Superhero",
  "Surfing",
  "Surreal Comedy",
  "Survival",
  "Swimming",
  "Swordplay",
  "Table Tennis",
  "Tanks",
  "Tanned Skin",
  "Teacher",
  "Teens' Love",
  "Tennis",
  "Terrorism",
  "Time Loop",
  "Time Manipulation",
  "Time Skip",
  "Tokusatsu",
  "Tomboy",
  "Torture",
  "Tragedy",
  "Trains",
  "Transgender",
  "Travel",
  "Triads",
  "Tsundere",
  "Twins",
  "Unrequited Love",
  "Urban",
  "Urban Fantasy",
  "VTuber",
  "Vampire",
  "Veterinarian",
  "Video Games",
  "Vikings",
  "Villainess",
  "Virtual World",
  "Vocal Synth",
  "Volleyball",
  "War",
  "Werewolf",
  "Wilderness",
  "Witch",
  "Work",
  "Wrestling",
  "Writing",
  "Wuxia",
  "Yakuza",
  "Yandere",
  "Youkai",
  "Yuri",
  "Zombie",
];

/**
 * The subset named in the companion's prompt — the high-signal themes,
 * settings and vibes people actually ask for. Kept short because it rides
 * along on every chat turn (token budget / rate limits); TAG_VOCAB above
 * still validates whatever the model returns.
 */
export const PROMPT_TAGS = [
  'Found Family', 'Coming of Age', 'Revenge', 'Tragedy', 'Time Loop', 'Time Manipulation', 'Reincarnation',
  'Isekai', 'Reverse Isekai', 'Magic', 'Super Power', 'Superhero', 'Mythology', 'Youkai', 'Demons', 'Gods',
  'Vampire', 'Zombie', 'Ghost', 'Curses', 'Exorcism', 'Alchemy', 'Cultivation', 'Wuxia', 'Fairy Tale',
  'Kaiju', 'Henshin', 'Real Robot', 'Super Robot', 'Space Opera', 'Space', 'Cyberpunk', 'Steampunk',
  'Dystopian', 'Post-Apocalyptic', 'Virtual World', 'Video Games', 'Death Game', 'Battle Royale', 'Survival',
  'War', 'Military', 'Politics', 'Philosophy', 'Conspiracy', 'Crime', 'Detective', 'Mafia', 'Yakuza',
  'Assassins', 'Espionage', 'Noir', 'Gore', 'Body Horror', 'Cosmic Horror', 'Iyashikei',
  'Cute Girls Doing Cute Things', 'Cute Boys Doing Cute Things', 'Family Life', 'Parenthood', 'Food', 'Travel',
  'Agriculture', 'Camping', 'Outdoor Activities', 'School', 'School Club', 'College', 'Work', 'Office', 'Idol',
  'Band', 'Rock Music', 'Classical Music', 'Dancing', 'Acting', 'Drawing', 'Writing', 'Fashion',
  'Otaku Culture', 'Animals', 'Medicine', 'Historical', 'Medieval', 'Samurai', 'Ninja', 'Swordplay',
  'Martial Arts', 'Guns', 'Pirates', 'Royal Affairs', 'Kingdom Management', 'Villainess', 'Anti-Hero',
  'Female Protagonist', 'Male Protagonist', 'Ensemble Cast', 'Primarily Adult Cast', 'Love Triangle',
  'Unrequited Love', 'Fake Relationship', 'Cohabitation', 'Female Harem', 'Yuri', "Boys' Love",
  'LGBTQ+ Themes', 'Episodic', 'Anthology', 'Parody', 'Satire', 'Slapstick', 'Surreal Comedy', 'Gambling',
  'Card Battle', 'E-Sports', 'Baseball', 'Basketball', 'Volleyball', 'Football', 'Tennis', 'Boxing',
  'Swimming', 'Cycling', 'Ice Sports', 'Bullying', 'Suicide', 'Disability', 'Amnesia', 'Memory Manipulation',
  'Artificial Intelligence', 'Robots', 'Aliens', 'Urban Fantasy', 'Rural', 'Achronological Order',
  'Delinquents', 'Chuunibyou',
].filter((t) => TAG_VOCAB.includes(t));
